{
 "title": "Netdata hosts overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement =~ /system.cpu$/)\n  |> group(columns:[\"hostname\"])\n  |> distinct(column:\"hostname\")\n  |> keep(columns: [\"_value\"])\n  |> group()"
   }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.cpu\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> last()\n  |> group()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_value: r.guest + r.guest_nice + r.iowait + r.irq + r.nice + r.softirq + r.steal + r.system + r.user }))"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r.hostname == \"$hostname\"\n    and r._field == \"load5\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 1 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.io\"\n    and r._field == \"in\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Net outbound",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.net\"\n    and r._field == \"sent\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r.hostname == \"$hostname\"\n    and r.type == \"disk_space\"\n    and r.family !~ /^\\/dev/\n    and r.family !~ /^\\/run/\n   )\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"family\"])\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ device: r.family, usage: (r.used / (r.used + r.avail)) }))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r._measurement == \"netdata.$hostname.system.uptime\" and\n    r._field == \"uptime\"\n  )\n  |> last()\n"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.ram\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> last()\n  |> group()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_value: ((r.used + r.buffers) / (r.free + r.used + r.cached + r.buffers)) * float(v: 100) }))"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r.hostname == \"$hostname\"\n    and r._field == \"load15\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 6 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.io\"\n    and r._field == \"out\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Net inbound",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 6 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.net\"\n    and r._field == \"received\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r._measurement == \"netdata.$hostname.netfilter.conntrack_sockets\"\n  )\n  |> last()\n"
    }
   ]
  }
 ]
}