{
 "title": "Netdata hosts details",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement =~ /system.cpu$/)\n  |> group(columns:[\"hostname\"])\n  |> distinct(column:\"hostname\")\n  |> keep(columns: [\"_value\"])\n  |> group()"
   },
   {
    "name": "containers",
    "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => \n    r.hostname == \"$hostname\"\n    and r.type =~ /^cgroup_.*/\n  )\n  |> group(columns:[\"type\"])\n  |> distinct(column:\"hostname\")\n  |> keep(columns: [\"type\"])\n  |> group()\n  |> map(fn: (r) => ({_value: r.type }))"
   },
   {
    "name": "cpu_count",
    "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement =~ /netdata.$hostname.cpu.cpu[0-9]*$/)\n  |> group()\n  |> distinct(column:\"_measurement\")\n  |> count()\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "disks",
    "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r._measurement =~ /netdata.cloud.disk.*$/\n    and r.type == \"disk\"\n    and r.family !~ /^\\//\n    and r.family !~ /^fd/\n  )\n  |> group()\n  |> distinct(column:\"family\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  { "title": "Current metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.cpu\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> last()\n  |> group()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_value: r.guest + r.guest_nice + r.iowait + r.irq + r.nice + r.softirq + r.steal + r.system + r.user }))"
    }
   ]
  },
  {
   "title": "Load5",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r.hostname == \"$hostname\"\n    and r._field == \"load5\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 1 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.io\"\n    and r._field == \"in\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Net outbound",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.net\"\n    and r._field == \"sent\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r.hostname == \"$hostname\"\n    and r.type == \"disk_space\"\n    and r.family !~ /^\\/dev/\n    and r.family !~ /^\\/run/\n   )\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"family\"])\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({ device: r.family, usage: (r.used / (r.used + r.avail)) }))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r._measurement == \"netdata.$hostname.system.uptime\" and\n    r._field == \"uptime\"\n  )\n  |> last()\n"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.ram\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> last()\n  |> group()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({_value: ((r.used + r.buffers) / (r.free + r.used + r.cached + r.buffers)) * float(v: 100) }))"
    }
   ]
  },
  {
   "title": "Load15",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) =>\n    r.hostname == \"$hostname\"\n    and r._field == \"load15\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Disk write",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 6 },
   "format": "KBs",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.io\"\n    and r._field == \"out\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Net inbound",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 6 },
   "format": "Kbits",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => \n    r._measurement == \"netdata.$hostname.system.net\"\n    and r._field == \"received\"\n  )\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range(start:-20m)\n  |> filter(fn: (r) =>\n    r._measurement == \"netdata.$hostname.netfilter.conntrack_sockets\"\n  )\n  |> last()\n"
    }
   ]
  },
  { "title": "CPU metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.cpu\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "CPU by apps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": " \nfrom(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.apps.cpu\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> map(fn: (r) => ({ r with _value: r._value / float(v: $cpu_count) }))"
    }
   ]
  },
  {
   "title": "CPU by users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.users.cpu\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> map(fn: (r) => ({ r with _value: r._value / float(v: $cpu_count) }))"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.load\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "System processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.processes\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Created processes/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.forks\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  { "title": "RAM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.ram\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.mem.available\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> map(fn: (r) => ({ r with _field: \"available\" }))"
    }
   ]
  },
  {
   "title": "Committed memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.mem.committed\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n  |> map(fn: (r) => ({ r with _field: \"committed\" }))"
    }
   ]
  },
  {
   "title": "Page fault/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.mem.pgfaults\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.swap\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.swapio\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  { "title": "Network metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Physical interface bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.net\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Connection tracker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.netfilter.conntrack_sockets\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "TCP connection aborts/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.ip.tcpconnaborts\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "TCP accept queue issues/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.ip.tcp_accept_queue\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  { "title": "Disk metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Total disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.system.io\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Apps open files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.apps.files\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Apps disk reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.apps.preads\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Apps disk writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.apps.pwrites\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  { "title": "Disk $disks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }, "repeat": "disks" },
  {
   "title": "I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.disk.$disks\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "I/O operations/s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.disk_ops.$disks\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Backlog",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.disk_backlog.$disks\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.disk_util.$disks\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  { "title": "Container $containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }, "repeat": "containers" },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.cgroup_$containers.cpu_limit\")\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "query": "from(bucket: \"netdata\")\n  |> range($range)\n  |> filter(fn: (r) => r._measurement == \"netdata.$hostname.cgroup_$containers.mem_usage_limit\")\n  |> keep(columns: [\"_time\", \"_value\", \"_field\"])\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}