name: Build and Release

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.14-alpine
    steps:
      - name: Install build-base
        run: apk add build-base
      - name: Install git
        run: apk add git
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build linux-amd64 variant
        run: go build -ldflags '-linkmode external -w -extldflags "-static"' -o netdata-influxdb-agent-amd64
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-agent-amd64
          path: netdata-influxdb-agent-amd64
      - name: Build linux-i386 variant
        run: GOARCH=386 go build -ldflags '-w' -o netdata-influxdb-agent-i386
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-agent-i386
          path: netdata-influxdb-agent-i386
      - name: Build linux-arm variant
        run: GOARCH=arm go build -ldflags '-w' -o netdata-influxdb-agent-arm
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-agent-arm
          path: netdata-influxdb-agent-arm
      - name: Build linux-arm64 variant
        run: GOARCH=arm64 go build -ldflags '-w' -o netdata-influxdb-agent-arm64
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-agent-arm64
          path: netdata-influxdb-agent-arm64
      - name: Create release note
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          previousTag=$(git tag --sort=committerdate | tail -2 | head -1)
          if [[ -z $previousTag ]]
          then
            git log --pretty=format:"- %s" > CHANGELOG.txt
          else
            git log --pretty=format:"- %s" $previousTag...${{ github.sha }} > CHANGELOG.txt
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.txt
          files: netdata-influxdb-agent*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  package:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    name: Package Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image
        run: docker build . --build-arg version=${GITHUB_REF:10} -t image
      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/netdata-influxdb-agent

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${GITHUB_REF:10}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION