name: Build and Release

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: golang:1.14-alpine
    steps:
      - name: Install build-base
        run: apk add build-base
      - name: Install git
        run: apk add git
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build linux-amd64 variant
        run: go build -ldflags '-linkmode external -w -extldflags "-static"' -o netdata-influxdb-relay-amd64
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-relay-amd64
          path: netdata-influxdb-relay-amd64
      - name: Build linux-i386 variant
        run: GOARCH=386 go build -ldflags '-w' -o netdata-influxdb-relay-i386
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-relay-i386
          path: netdata-influxdb-relay-i386
      - name: Build linux-arm variant
        run: GOARCH=arm go build -ldflags '-w' -o netdata-influxdb-relay-arm
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-relay-arm
          path: netdata-influxdb-relay-arm
      - name: Build linux-arm64 variant
        run: GOARCH=arm64 go build -ldflags '-w' -o netdata-influxdb-relay-arm64
      - uses: actions/upload-artifact@v1
        with:
          name: netdata-influxdb-relay-arm64
          path: netdata-influxdb-relay-arm64
      - name: Create release note
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          previousTag=$(git tag --sort=committerdate | tail -2 | head -1)
          if [[ -z $previousTag ]]
          then
            git log --pretty=format:"- %s" > CHANGELOG.txt
          else
            git log --pretty=format:"- %s" $previousTag...${{ github.sha }} > CHANGELOG.txt
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.txt
          files: netdata-influxdb-relay*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}